name: news_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:

  #PATTERNS
  dartz: ^0.10.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  intl: ^0.18.1
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7
  get_it: ^7.6.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0
  flutter_lints: 3.0.1
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  mockito: ^5.4.2
  bloc_test: ^9.1.3
  fake_cloud_firestore: 2.4.3
  firebase_storage_mocks: ^0.6.1
  bdd_widget_test: ^1.6.0
  flutter_gherkin: ^2.0.0
  firebase_core_platform_interface: 5.0.0
  firebase_auth_mocks: 0.13.0

flutter: