name: Issue Notification

on:
  issues:
    types: [opened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_EMBEDS: '[{
                "author": {
                  "icon_url": "https://avatars.githubusercontent.com/${{ github.actor }}",
                  "name": "${{ github.actor }}",
                  "url": "https://github.com/${{github.actor}}"
                },
                "url": "https://github.com/${{github.repository}}/issues/${{github.event.issue.number}}",
                "title": "Novo Issue: #${{github.event.issue.number}}",
                "description": "${{github.event.issue.title}}",
                "fields": [
                  { "name": "Repository", "value": "[${{github.repository}}](https://github.com/${{github.repository}})", "inline": true },
                  { "name": "Author", "value": "[${{github.event.issue.user.login}}](https://github.com/${{github.event.issue.user.login}})", "inline": true }
                ],
                "color": 1127128,
                "timestamp": "${{github.event.issue.created_at}}",
                "footer": { "text": "Issue created at: ${{github.event.issue.created_at}}" }
              }]'
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_AVATAR: https://cdn.theatlantic.com/thumbor/FPTWEk2jCD_GOlSx-Q3p04tDPOk=/302x50:4317x2308/1600x900/media/img/mt/2014/08/shutterstock_187027727-1/original.jpg
